In [1]:
#7/01/2025

In [2]:
import numpy as np

In [3]:
data=[10,20,30,40,50]
arr=np.array(data)
print(arr)

[10 20 30 40 50]


In [4]:
d2=[[1,2,3],[4,5,6],[7,8,9,10]]

In [6]:
arr2=np.array(d2)
print(arr2) #as elements are not equally in each dimensions.IT gives error .

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (3,) + inhomogeneous part.

In [7]:
np.random.rand()  #Uniform Distribution

0.34602421385870397

In [8]:
np.random.rand(10)  #1D array

array([0.11738882, 0.31480957, 0.56381232, 0.43405013, 0.29567788,
       0.39557407, 0.60236137, 0.70267637, 0.83139723, 0.90993607])

In [9]:
np.random.rand(4,5)  #2D array  
#here we have defined that 4 rows and 5 columns
#so in the range 0 to 1 it gives 20 numbers 

array([[0.43196544, 0.83165096, 0.43200351, 0.0919173 , 0.37447236],
       [0.5042812 , 0.28891339, 0.46855196, 0.31230173, 0.64472898],
       [0.29658536, 0.49046711, 0.99941245, 0.54734987, 0.90401823],
       [0.61893928, 0.14043336, 0.25910252, 0.80623405, 0.25077065]])

In [10]:
np.random.randn()  #standard normal distribution(mean is 0 and SD is 1)

1.5119893936724706

random.rand() ->gives for uniform distribution ie between 0 to 1 range 

random.randn() -> gives for standard normal distribution ie -1 to 1 range

In [11]:
np.random.randn(12) #from -1 to 1

array([ 1.18620496,  0.8929972 ,  0.68901493, -0.41676708, -1.65323753,
        1.28644361, -0.25795725,  0.70432345,  0.00258904, -0.39931211,
       -0.89100607,  0.1255645 ])

In [12]:
np.random.randn(4,5)
#here we have defined that 4 rows and 5 columns
#so in the range -1 to 1 it gives 20 numbers 

array([[ 0.44837168,  0.01385462, -0.56231971,  0.46956521,  0.84937933],
       [-0.78656661,  0.02474199,  0.35378405, -0.76769709,  0.5886887 ],
       [-0.27374432, -1.40977403, -0.21621815,  0.46817092,  0.52379779],
       [ 0.17057428,  0.50740252, -0.62761895,  0.99933526, -0.65338078]])

In [13]:
np.random.randint(1) #this will give 1 random integer 

0

In [14]:
np.random.randint(5)

0

In [15]:
np.random.randint(5)


1

In [16]:
np.random.randint(5)


3

In [17]:
np.random.randint(5,20)
#here we are difining range from 5 to 20 give 1 random integer 

7

In [18]:
np.random.randint(5,20,6) #any six random int between 5 to 20


array([12, 14,  5,  8, 17, 18])

In [19]:
#rand
#randn
#randint


In [20]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
np.arange(10,100)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60,
       61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [22]:
np.arange(10,100,5) #arange is like from 10 to 100 at the jump of 5 give numbers .It is similar to for loop 

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [23]:
np.arange(1,26)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [24]:
np.arange(1,26).reshape(4,5) #Error

ValueError: cannot reshape array of size 25 into shape (4,5)

In [25]:
np.arange(1,26).reshape(5,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [26]:
np.arange(1,26).reshape(1,25) #1 array ie 1->2D array having 25 elements 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24, 25]])

In [27]:
np.arange(1,26).reshape(25,1) #25 rows and 1 column

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24],
       [25]])

In [28]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [29]:
arr.shape

(5, 5)

In [30]:
arr.ndim

2

In [31]:
a1=np.arange(1,26)
a1.shape

(25,)

In [32]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [33]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [35]:
np.ones((4,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
np.ones(5)*4

array([4., 4., 4., 4., 4.])

In [37]:
np.zeros(5)+4

array([4., 4., 4., 4., 4.])

In [38]:
#identity matrix ==> only principle diagonal elements are 1 i.e.A11, A22, A33

In [39]:
np.eye(10) #2D

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [40]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [41]:
np.eye(4,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [42]:
np.identity((4,5))

TypeError: 'tuple' object cannot be interpreted as an integer

In [43]:
np.linspace(0,10,3)  #linearly spaced element
#it give from 0 to 10 3 elements at equal space ie linesrly spaced 

array([ 0.,  5., 10.])

In [44]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [45]:
np.linspace(10,100,50)

array([ 10.        ,  11.83673469,  13.67346939,  15.51020408,
        17.34693878,  19.18367347,  21.02040816,  22.85714286,
        24.69387755,  26.53061224,  28.36734694,  30.20408163,
        32.04081633,  33.87755102,  35.71428571,  37.55102041,
        39.3877551 ,  41.2244898 ,  43.06122449,  44.89795918,
        46.73469388,  48.57142857,  50.40816327,  52.24489796,
        54.08163265,  55.91836735,  57.75510204,  59.59183673,
        61.42857143,  63.26530612,  65.10204082,  66.93877551,
        68.7755102 ,  70.6122449 ,  72.44897959,  74.28571429,
        76.12244898,  77.95918367,  79.79591837,  81.63265306,
        83.46938776,  85.30612245,  87.14285714,  88.97959184,
        90.81632653,  92.65306122,  94.48979592,  96.32653061,
        98.16326531, 100.        ])

In [46]:
arr=np.arange(1,26).reshape(5,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [47]:
arr[[0,3],[1,3]]

#You're telling NumPy to get the elements at (0,1) and (3,3):

#arr[0, 1] → row 0, column 1 → 2

#arr[3, 3] → row 3, column 3 → 19

#arr[[0,3],[1,3]] → [arr[0,1], arr[3,3]] → [2, 19]

array([ 2, 19])

In [48]:
np.arange(0.01, 1.01,0.01).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [49]:
np.linspace(0.01,1,100).reshape(10,10)

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [50]:
#this is manually we can done but not supported for large dataset
arr=np.zeros((10,10))
arr[1:]=1
arr[2:]=2
arr[3:]=3
arr[4:]=4
arr[5:]=5
arr[6:]=6
arr[7:]=7
arr[8:]=8
arr[9:]=9
arr

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [51]:
arr=np.zeros((10,10))
for i in range(10):
    arr[i]+=i
arr    

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [52]:
#Numpy array supports broadcasting

In [53]:
arr=np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [54]:
arr_subset=arr[5:12]

In [55]:
arr_subset

array([ 6,  7,  8,  9, 10, 11, 12])

In [56]:
arr_subset[1:5]=89

In [57]:
arr

array([ 1,  2,  3,  4,  5,  6, 89, 89, 89, 89, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [58]:
arr_subset

array([ 6, 89, 89, 89, 89, 11, 12])

In [59]:
arr_copy=arr.copy()

In [60]:
arr_copy

array([ 1,  2,  3,  4,  5,  6, 89, 89, 89, 89, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [61]:
arr=np.arange(1,26)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25])

In [62]:
arr2d=arr.reshape(5,5)
arr2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [63]:
arr2d.sum()

325

In [64]:
arr2d.sum(axis=0)

array([55, 60, 65, 70, 75])

In [65]:
arr2d.sum(axis=1)


array([ 15,  40,  65,  90, 115])

In [66]:
#6599900